import type { PartyCatalogItem } from "@/party/lib/types";

export const PARTY_SEED_ITEMS: PartyCatalogItem[] = [
  {
    id: "seed-bier-sixpack",
    category: "Getränk",
    title: "Bier",
    note: "Am liebschte e chli spannend und nid nume Standard-Lager.",
    unitLabel: "Sixpack",
    targetQuantity: 4,
    sortOrder: 10,
    isCustom: false,
  },
  {
    id: "seed-bier-alkfrei",
    category: "Getränk",
    title: "Bier alkoholfrei",
    note: "Für alli, wo stylish aber nüechter underwägs si.",
    unitLabel: "Sixpack",
    targetQuantity: 2,
    sortOrder: 20,
    isCustom: false,
  },
  {
    id: "seed-weisswy",
    category: "Getränk",
    title: "Wiisswy",
    note: "Troche oder naturtrüeb, beides sehr akzeptabel.",
    unitLabel: "Fläsche",
    targetQuantity: 3,
    sortOrder: 30,
    isCustom: false,
  },
  {
    id: "seed-rotwy",
    category: "Getränk",
    title: "Rotwy",
    note: "Eher öppis, wo me ou würklich trinke wott.",
    unitLabel: "Fläsche",
    targetQuantity: 3,
    sortOrder: 40,
    isCustom: false,
  },
  {
    id: "seed-prosecco",
    category: "Getränk",
    title: "Prosecco / Schum",
    note: "Cha ou Cava, Pet Nat oder random Schranz mit Blöterli si.",
    unitLabel: "Fläsche",
    targetQuantity: 3,
    sortOrder: 50,
    isCustom: false,
  },
  {
    id: "seed-chips-nature",
    category: "Snack",
    title: "Chips Nature",
    note: "Bieder, aber zuverlässig.",
    unitLabel: "Pack",
    targetQuantity: 4,
    sortOrder: 60,
    isCustom: false,
  },
  {
    id: "seed-chips-paprika",
    category: "Snack",
    title: "Chips Paprika",
    note: "Für d Leit mit rotem Gaume.",
    unitLabel: "Pack",
    targetQuantity: 4,
    sortOrder: 70,
    isCustom: false,
  },
  {
    id: "seed-vegi-wurst",
    category: "Grillgut",
    title: "Vegi Würst",
    note: "Bitte vegan, bitte guet, bitte nid Karton.",
    unitLabel: "Pack",
    targetQuantity: 4,
    sortOrder: 80,
    isCustom: false,
  },
  {
    id: "seed-vegi-burger",
    category: "Grillgut",
    title: "Vegi Burger-Patties",
    note: "Eher chunnt öpper mit zwenig als mit zvil.",
    unitLabel: "Pack",
    targetQuantity: 4,
    sortOrder: 90,
    isCustom: false,
  },
  {
    id: "seed-tofu",
    category: "Grillgut",
    title: "Marinierte Tofu-Stück",
    note: "Bitte nid ungwürzt us em Kühli use direkt i d Truurigkeit.",
    unitLabel: "Pack",
    targetQuantity: 3,
    sortOrder: 100,
    isCustom: false,
  },
  {
    id: "seed-seitan",
    category: "Grillgut",
    title: "Seitan / Planted-Zügs",
    note: "Für d Proteinfraktion mit Hut.",
    unitLabel: "Pack",
    targetQuantity: 3,
    sortOrder: 110,
    isCustom: false,
  },
  {
    id: "seed-grillgemuese",
    category: "Grillgut",
    title: "Grillgmües",
    note: "Zucchetti, Peperoni, Pilz, Mais, Aubergine, du wosch drill.",
    unitLabel: "Schüssle",
    targetQuantity: 4,
    sortOrder: 120,
    isCustom: false,
  },
  {
    id: "seed-hummus",
    category: "Beilagen",
    title: "Hummus",
    note: "Eifach, aber elementar.",
    unitLabel: "Schüssle",
    targetQuantity: 3,
    sortOrder: 130,
    isCustom: false,
  },
  {
    id: "seed-baguette",
    category: "Beilagen",
    title: "Brot / Baguette",
    note: "Lieber meh als zwenig. S Brot löscht manchi Problem.",
    unitLabel: "Pack",
    targetQuantity: 5,
    sortOrder: 140,
    isCustom: false,
  },
  {
    id: "seed-dips",
    category: "Beilagen",
    title: "Vegani Dips / Sauce",
    note: "Chnobli, Kräuter, Schärfe, irgend öppis mit Charakter.",
    unitLabel: "Schüssle",
    targetQuantity: 4,
    sortOrder: 150,
    isCustom: false,
  },
  {
    id: "seed-guacamole",
    category: "Beilagen",
    title: "Guacamole",
    note: "Wenn öpper rich ufgwacht isch.",
    unitLabel: "Schüssle",
    targetQuantity: 2,
    sortOrder: 160,
    isCustom: false,
  },
  {
    id: "seed-salat",
    category: "Beilagen",
    title: "Salat gross",
    note: "Bitte e Salat und nid nume e Symbolhandlung.",
    unitLabel: "Schüssle",
    targetQuantity: 3,
    sortOrder: 170,
    isCustom: false,
  },
  {
    id: "seed-pastasalat",
    category: "Beilagen",
    title: "Pastasalat vegan",
    note: "Darf ou leicht trashy si, we me ehrlich isch.",
    unitLabel: "Schüssle",
    targetQuantity: 3,
    sortOrder: 180,
    isCustom: false,
  },
  {
    id: "seed-kartoffelsalat",
    category: "Beilagen",
    title: "Härdöpfusalat vegan",
    note: "Mit Substanz. Nid nume e Wässerschüssle mit Chnolle.",
    unitLabel: "Schüssle",
    targetQuantity: 3,
    sortOrder: 190,
    isCustom: false,
  },
  {
    id: "seed-wraps",
    category: "Beilagen",
    title: "Wraps / Fladebrot",
    note: "Für alli, wo gärn no chli baue am Täller.",
    unitLabel: "Pack",
    targetQuantity: 3,
    sortOrder: 200,
    isCustom: false,
  },
  {
    id: "seed-fruchtsalat",
    category: "Dessert",
    title: "Fruchtsalat",
    note: "Bringt Vitamin i d dekorativi Verwahrlosig.",
    unitLabel: "Schüssle",
    targetQuantity: 2,
    sortOrder: 210,
    isCustom: false,
  },
  {
    id: "seed-muffins",
    category: "Dessert",
    title: "Vegani Chueche / Muffins",
    note: "Wenns e chli z schön isch, stört das niemer.",
    unitLabel: "Portion",
    targetQuantity: 3,
    sortOrder: 220,
    isCustom: false,
  },
  {
    id: "seed-sorbet",
    category: "Dessert",
    title: "Sorbet / vegani Glace",
    note: "Bitte mit Chüeltäsche-Hustle.",
    unitLabel: "Pack",
    targetQuantity: 2,
    sortOrder: 230,
    isCustom: false,
  },
  {
    id: "seed-schoggi",
    category: "Dessert",
    title: "Schoggi / vegans Süesses",
    note: "Für s moralische Gleichgwicht.",
    unitLabel: "Pack",
    targetQuantity: 3,
    sortOrder: 240,
    isCustom: false,
  },
];

